### ISSUE TITLE
Is there a limitation on 5 connected sensors?

### ISSUE THREAD

**Issue by FrederikPetri** [xsens/xsens_dot_server#10]
Is there some limitation in the code that makes it impossible to connect to >5 sensors?

**Comment by freddijkstra** [comment]
No, there is no limit imposed on the number of sensors. We've been testing with over 8 sensors on a Mac for example. The limitation of the number of sensors is determined by the capacity of the used Bluetooth adapter. Maybe there's a hint on the maximum number in the specifications of the adapter?

**Comment by FrederikPetri** [comment]
Hi Fred,

Thanks for the hint. The specifications says 6 Bluetooth devices, so I guess thats the limitation.
