### ISSUE TITLE
Unable to connect multiple dots in Raspberry pi 4 

### ISSUE THREAD

**Issue by naveenkumar2095** [xsens/xsens_dot_server#14]
Hello,

I am trying to connect multiple dots at same time using raspberry pi 4 model but unable to achieve this task. due to some issue, one sensor connect at a time and rest of the sensors  continuously  showing  "stop connecting " in the GUI. let me how to rectify this problem.

Best Regards
R Naveen kumar 
NXtQ Pvt Ltd
![pi41](https://user-images.githubusercontent.com/61741018/96679800-fe25ae00-1391-11eb-9381-7b148a8b49cf.png)
![61](https://user-images.githubusercontent.com/61741018/96680070-71c7bb00-1392-11eb-9088-dab6bcafa8e5.PNG)

**Comment by fancycww** [comment]
Hi,
It seems that you used the old firmware 1.0.0.
Could you please check the version of the firmware?
Please use the latest version 1.4.0.
Thanks.

**Comment by naveenkumar2095** [comment]
Hello

Thank you for your response. Ya checked in the readme file it's mentioned
version 1.4.0

Regards
Naveen Kumar
NxtQ Pvt Ltd

**Comment by naveenkumar2095** [comment]
Please find the screenshots attached in the github issues it is
clearly showing code issue in blehandler.js
Best Regards
R Naveen Kumar

**Comment by naveenkumar2095** [comment]
If it is failure because of firmware version, Can you please send me the procedure to upgrade the version to 1.4.0?

**Comment by gnixob** [comment]
> If it is failure because of firmware version, Can you please send me the procedure to upgrade the version to 1.4.0?

Hi, please follow these steps:
1. Download "Xsens DOT" app from Google play store or App store
2. Connect the senors
3. Go to "Advance - Device Firmware Upgrade"
4. Follow the instructions in the app to do the upgrade.

Thanks!

**Comment by naveenkumar2095** [comment]
Thank you for your response 

Best regards 
Naveen kumar
NxtQ Pvt Ltd
