### ISSUE TITLE
Unable to record and fail to get log file

### ISSUE THREAD

**Issue by naveenkumar2095** [xsens/xsens_dot_server#15]
Hello,

I connected single dot to raspberry pi 4 model , unable to collect log file using Xsens_dot_server source code. Please let me know how to get that. In the GUI it showing continuously sync..state. 
![pi42](https://user-images.githubusercontent.com/61741018/96680894-fa932680-1393-11eb-8c49-9d6c74e8d76e.png)

**Comment by fancycww** [comment]
Hi,
Could you please check the version of the firmware?
Please use the latest firmware version 1.4.0 that we supported syncing.
Thanks.

**Comment by naveenkumar2095** [comment]
Thank you for your response , now it is working fine.

Best Regards 
Naveenkumar
NxtQ Pvt Ltd
