### ISSUE TITLE
How to upgrade dots with out using Xsens dot app

### ISSUE THREAD

**Issue by naveenkumar2095** [xsens/xsens_dot_server#17]
Can we able to upgrade dots using raspberry pi ? let me know if any alternative method.

Best Regards 
Naveen Kumar 
NxtQ Pvt Ltd

**Comment by gnixob** [comment]
Hi,

You can only upgrade the DOT with Xsens DOT app (available on google play store and app store). A new function in SDK that gives out notification when new firmware version is available will be released soon. Though you still need to go to Xsens DOT app to do the upgrade/downgrade.

Hope this helps.
