### ISSUE TITLE
Server works fine on Raspberry Pi 3 Model B+

### ISSUE THREAD

**Issue by aero-man** [xsens/xsens_dot_server#3]
I saw that the README has an option to use a Raspberry Pi 4 Model B run the server. For documentation purposes, I installed it on my Raspberry Pi 3 Model B+ and ran it without issue. Server starts up, connects to sensors, and logs data just fine.

Specs:
Raspberry Pi 3 Model B+
1 GB RAM
Raspberry Pi OS (Raspbian), Version: May 2020, Kernel: 4.19

**Comment by freddijkstra** [comment]
Yes, that's correct. Documentation should state Raspberry Pi 3 as well. I'm using that platform also.

**Comment by gnixob** [comment]
Thanks for this info! Will update in the documentation.
