### ISSUE TITLE
The server does not connect to sensors on RPi 4

### ISSUE THREAD

**Issue by mohse-n** [xsens/xsens_dot_server#6]
I'm using RPi 4. On the browser GUI, I can start scanning and it does find the sensors. When I select Connect, however, it does not connect to the any of the sensors. I'm not getting any error messages.

**Comment by fancycww** [comment]
Mohse was using the latest version of RPi OS to fixed this issue, see more details:
https://base.xsens.com/hc/en-us/community/posts/360009645740-Can-t-start-measurement-with-Noble?page=1#community_comment_360002190000
