### ISSUE TITLE
Error when starting scanning

### ISSUE THREAD

**Issue by FrederikPetri** [xsens/xsens_dot_server#9]
I get the error: "ERROR: component 'SensorServer' received unexpected event 'startScanning' in state 'Powering-on'" when starting scanning for the sensors. Can you help me solve this?

**Comment by freddijkstra** [comment]
Enable your Bluetooth?

**Comment by FrederikPetri** [comment]
Hi Fred,

I followed the guide and changed my Bluetooth driver to WinUSB. It should be enabled when I look it up in Device Manager?
![fdsf](https://user-images.githubusercontent.com/58137256/94791468-f6e53300-03d7-11eb-8748-250828177158.PNG)

**Comment by freddijkstra** [comment]
As I'm not familiar with Windows (I use Mac), I unfortunately cannot give you advise on that area. However, the error occurs when the Bluetooth adapter is not enabled (I agree that the error is not descriptive :-). So either the installation failed, the wrong adapter is used or some other Windows related problem persists.
